language: ruby

sudo: false

dist: trusty

rvm:
  - 2.3.4
  - 2.4.1

addons:
  apt:
    packages:
      - libopencv-dev

env:
  global:
    - PATH=/usr/lib/ccache:$PATH

cache:
  bundler: true
  directories:
    - $HOME/.ccache

before_script:
  - ruby ext/opencv/extconf.rb
  - make
  - make install

script:
  - cd test
  - ruby runner.rb
