platform: mingw32
rubies:
  - C:/ruby-1.9.3-p392-mingw32/bin/ruby.exe
  - C:/ruby-2.0.0-p0-mingw32/bin/ruby.exe
extopts:
  - --with-opencv-include=C:/opencv-2.4.5/build/include
  - --with-opencv-lib=C:/opencv-2.4.5/build/x86/mingw/lib
